### ISSUE TITLE
Responsiveness needed

### ISSUE THREAD

**Issue by singhayushh** [singhayushh/Bibleo#11]
Hello, 
Currently the website lacks responsiveness for narrower screens, across all pages. 

Contributions are welcome!

**Comment by oxavibes** [comment]
Hi @singhayushh, let me help you with this

**Comment by singhayushh** [comment]
Sure! 
Would you like me to assign you this issue?

**Comment by oxavibes** [comment]
Sure

**Comment by oxavibes** [comment]
Could you upload your database somewhere? Or send it to bozzistef@gmail.com

**Comment by singhayushh** [comment]
@oxavibes 
It's recommended to create a free cluster from MongoDB Atlas under your own account and connect it for development and testing purposes

Let me know if you have any problem regarding that.

**Comment by satyamasthanaa** [comment]
I would like to contribute to this, please assign me this task.

**Comment by singhayushh** [comment]
@satyamasthanaa 
There is already one asignee. Please have a talk with him if he wants a collaborator 😅

**Comment by oxavibes** [comment]
Hi @singhayushh , do you have the example .env file? I just started to work on this

**Comment by singhayushh** [comment]
Mailed.

**Comment by oxavibes** [comment]
Hi @singhayushh, you can assign this to @satyamasthanaa if you want, I have been busy at work these days 😞
