### ISSUE TITLE
Broken Frontend

### ISSUE THREAD

**Issue by singhayushh** [singhayushh/Bibleo#7]
Go throught the [Contribution guidelines](https://github.com/singhayushh/project_Bookmarks/blob/master/contributing.md)  before making any changes

> Send PRs only after October 1st to make it count as a valid PR for hacktober fest'20

### The Issue
I have been developing this project to learn NodeJS-Express-Mongo, so I didn't pay much attention to the frontend side, majority of which is unresponsive and incomplete. While I'm working with the backend, it would be very helpful if the frontend part gets developed side by side.
Missing: user profile page, bookmark page, tag-pages, animations
Issues: Unresponsive
> No Javascript frameworks are in the current project used but just plain html (in the form of ejs), css and js for the frontend side.

### Little help with ejs
If you aren't experienced with ejs, I've used EJS mostly for putting values from backend along with some if-else blocks and for loops inside HTML.
You may have a look at the [dashboard.ejs](https://github.com/singhayushh/project_Bookmarks/blob/master/views/dashboard.ejs) file to see how to use the variables being passed from backend.

**Comment by resparx** [comment]
Hey hi @singhayushh , shall i step in to check your problem or it is fixed ?
I've read the contribution guidelines, please let me know once you see this.

**Comment by singhayushh** [comment]
> Hey hi @singhayushh , shall i step in to check your problem or it is fixed ?
> I've read the contribution guidelines, please let me know once you see this.

Thanks for connecting,
I kinda fixed the responsiveness issues for desktop screens as well as added few more missing webpages
The project currently lacks 
- Responsiveness for mobile screens.
- User profile page
- A page that would show books categorized under different tags

Kindly send PRs if interested only after October 1st as I wouldn't be able to attend to PRs before that date, in support of HacktoberFest 😓 
> As I was making this project earlier this year to learn backend, I would prefer contributions to be on the frontend side only.
